services:
  backend:
    container_name: studymate-asp-dot-net
    build:
      context: ../studymate-backend
      dockerfile: Dockerfile.dev
    ports:
      - "5000:5000"
    volumes:
      - ../studymate-backend:/app
    networks:
      - studymate-network

  frontend:
    container_name: studymate-node-angular
    build:
      context: ../studymate-frontend
      dockerfile: Dockerfile.dev
    ports:
      - "4200:4200"
    volumes:
      - ../studymate-frontend:/app
      - studymate-node-modules:/app/node_modules
    depends_on:
      - backend
    networks:
      - studymate-network

  database:
    container_name: studymate-postgres
    image: postgres:16-alpine
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - studymate-postgres:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_DB: studymate
      POSTGRES_USER: studymate
      POSTGRES_PASSWORD: studymate
      PGDATA: /var/lib/postgresql/data
    networks:
      - studymate-network

  database-administration:
    container_name: studymate-postgres-admin
    image: dpage/pgadmin4:8
    restart: always
    ports:
      - "5050:80"
    volumes:
      - studymate-pgadmin:/var/lib/pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: studymate@studymate.com
      PGADMIN_DEFAULT_PASSWORD: studymate
      PGADMIN_CONFIG_SERVER_MODE: "False"
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: "False"
      PGADMIN_LISTEN_PORT: 80
    depends_on:
      - database
    networks:
      - studymate-network
    user: root
    entrypoint: /bin/sh -c "chmod 600 /pgpass; /entrypoint.sh;"
    configs:
      - source: pgpass
        target: /pgpass
      - source: servers
        target: /pgadmin4/servers.json

configs:
  pgpass:
    content: database:5432:*:studymate:studymate
  servers:
    content: |
      {"Servers": {"1": {
        "Group": "Servers",
        "Name": "PostgreSQL StudyMate Development",
        "Host": "database",
        "Port": 5432,
        "MaintenanceDB": "studymate",
        "Username": "studymate",
        "PassFile": "/pgpass",
        "SSLMode": "prefer"
      }}}

networks:
  studymate-network:
    driver: bridge

volumes:
  studymate-asp-dot-net-build:
  studymate-node-modules:
  studymate-postgres:
  studymate-pgadmin: