services:
  backend:
    container_name: studymate-asp-dot-net
    build:
      context: ../studymate-backend
      dockerfile: Dockerfile.dev
    ports:
      - "5000:5000"
    depends_on:
      - database
    volumes:
      - ../studymate-backend/studymate-backend:/app/studymate-backend
      - studymate-nuget:/app/studymate-backend/obj
      - studymate-nuget:/app/studymate-backend/bin
      - ../studymate-backend/studymate-backend-tests:/app/studymate-backend-tests
      - studymate-nuget:/app/studymate-backend-tests/obj
      - studymate-nuget:/app/studymate-backend-tests/bin
    networks:
      - studymate-network

  frontend:
    container_name: studymate-node-angular
    build:
      context: ../studymate-frontend
      dockerfile: Dockerfile.dev
    ports:
      - "4200:4200"
    volumes:
      - ../studymate-frontend:/app
      - studymate-node-modules:/app/node_modules
    depends_on:
      - backend
    networks:
      - studymate-network

  database:
    container_name: studymate-mysql
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: studymate
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    volumes:
      - studymate-mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"

  phpmyadmin:
    container_name: studymate-phpmyadmin
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: database
      PMA_USER: admin
      PMA_PASSWORD: admin
      UPLOAD_LIMIT: 300M
    ports:
      - "8081:80"
    depends_on:
      - database

networks:
  studymate-network:
    driver: bridge

volumes:
  studymate-asp-dot-net-build:
  studymate-node-modules:
  studymate-mysql-data:
  studymate-nuget:
