services:
  backend:
    container_name: studymate-asp-dot-net
    build:
      context: ../studymate-backend
      dockerfile: Dockerfile.dev
    ports:
      - "${BACKEND_PORT}:8080"
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_SERVER: ${MYSQL_SERVER}
      MYSQL_USER: ${MYSQL_USER}

      SMTP_EMAIL: ${SMTP_EMAIL}
      SMTP_PASSWORD: ${SMTP_PASSWORD}

      OAUTH_CLIENT_ID: ${OAUTH_CLIENT_ID}
      OAUTH_CLIENT_SECRET: ${OAUTH_CLIENT_SECRET}
      OAUTH_REDIRECT_URI: ${OAUTH_REDIRECT_URI}
      OAUTH_ENDPOINT_USER_INFO: ${OAUTH_ENDPOINT_USER_INFO}

      OAUTH2_ENDPOINT: ${OAUTH2_ENDPOINT}
      OAUTH2_ENDPOINT_TOKEN: ${OAUTH2_ENDPOINT_TOKEN}
      OAUTH2_ENDPOINT_USER_INFO: ${OAUTH2_ENDPOINT_USER_INFO}
    depends_on:
      - database
    volumes:
      - ../studymate-backend/studymate-backend:/app/studymate-backend
      - studymate-nuget:/app/studymate-backend/obj
      - studymate-nuget:/app/studymate-backend/bin
      - ../studymate-backend/studymate-backend-tests:/app/studymate-backend-tests
      - studymate-nuget:/app/studymate-backend-tests/obj
      - studymate-nuget:/app/studymate-backend-tests/bin
    networks:
      - studymate-network

  frontend:
    container_name: studymate-node-angular
    build:
      context: ../studymate-frontend
      dockerfile: Dockerfile.dev
    ports:
      - "4200:4200"
    volumes:
      - ../studymate-frontend:/app
      - studymate-node-modules:/app/node_modules
    depends_on:
      - backend
    networks:
      - studymate-network

  database:
    container_name: studymate-mysql
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_SERVER: ${MYSQL_SERVER}
      MYSQL_USER: ${MYSQL_USER}
    networks:
      - studymate-network
    volumes:
      - studymate-mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"

  phpmyadmin:
    container_name: studymate-phpmyadmin
    image: phpmyadmin:latest
    environment:
      PMA_HOST: ${PMA_HOST}
      PMA_USER: ${PMA_USER}
      PMA_PASSWORD: ${PMA_PASSWORD}
      UPLOAD_LIMIT: 300M
    networks:
      - studymate-network
    ports:
      - "8081:80"
    depends_on:
      - database

networks:
  studymate-network:
    driver: bridge

volumes:
  studymate-asp-dot-net-build:
  studymate-node-modules:
  studymate-mysql-data:
  studymate-nuget:
